# Teste Power BI report em Jupyter Notebook

In [13]:
from powerbiclient import QuickVisualize, get_dataset_config, Report
from powerbiclient.authentication import DeviceCodeLoginAuthentication
from powerbiclient.authentication import InteractiveLoginAuthentication
import pandas as pd

In [14]:
df = pd.read_csv('Financial Sample.csv')

In [15]:
df

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Montana,High,200.0,5,350,70000.0,9800.00,60200.00,52000.0,8200.00,5/1/2014,5,May,2014
1,Small Business,Germany,Carretera,Low,214.0,3,300,64200.0,1284.00,62916.00,53500.0,9416.00,10/1/2013,10,October,2013
2,Small Business,Germany,VTT,Low,214.0,250,300,64200.0,1284.00,62916.00,53500.0,9416.00,10/1/2013,10,October,2013
3,Midmarket,Canada,Paseo,Low,218.0,10,15,3270.0,130.80,3139.20,2180.0,959.20,9/1/2014,9,September,2014
4,Government,Germany,Paseo,High,241.0,10,20,4820.0,482.00,4338.00,2410.0,1928.00,10/1/2014,10,October,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Channel Partners,Canada,Paseo,High,4026.0,10,12,48312.0,5314.32,42997.68,12078.0,30919.68,7/1/2014,7,July,2014
696,Enterprise,Germany,Amarilla,NaN,4219.5,260,125,527437.5,0.00,527437.50,506340.0,21097.50,4/1/2014,4,April,2014
697,Enterprise,France,Carretera,Low,4243.5,3,125,530437.5,15913.13,514524.38,509220.0,5304.38,4/1/2014,4,April,2014
698,Government,Canada,Paseo,Low,4251.0,10,7,29757.0,1190.28,28566.72,21255.0,7311.72,1/1/2014,1,January,2014
699,Government,United States of America,Paseo,Low,4492.5,10,7,31447.5,314.48,31133.03,22462.5,8670.53,4/1/2014,4,April,2014

In [16]:
auth = InteractiveLoginAuthentication()

A local browser window will open for interactive sign in.

Interactive authentication successfully completed.
You are now logged in.

The result should be passed only to trusted code in your notebook.

In [17]:
PBI_visualize = QuickVisualize(get_dataset_config(df), auth=auth)

In [18]:
PBI_visualize

QuickVisualize()